# Generated by Django 4.2 on 2025-02-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
