# Generated by Django 4.2 on 2025-02-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0002_content_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
