# Generated by Django 4.2 on 2025-02-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0003_content_play_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='play_count',
        ),
    ]
