# Generated by Django 5.1.6 on 2025-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0006_category_content_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
