# Generated by Django 4.2 on 2025-02-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0008_alter_category_id_alter_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
