# Generated by Django 5.1.6 on 2025-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
